module.exports = [
"[project]/Documents/Projects/getsucces/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {

// import type { Metadata } from "next";
// import "./globals.css";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
}),
];

//# sourceMappingURL=Documents_Projects_getsucces_app_layout_tsx_30c94e94._.js.map