var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/Documents_Projects_getsucces_b0d53053._.js")
R.c("server/chunks/ssr/Documents_Projects_getsucces_399b3476._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ae817249._.js")
R.c("server/chunks/ssr/Documents_Projects_getsucces_5177071d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09e22fe6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__023fd315._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d9bc459._.js")
R.c("server/chunks/ssr/51311_next_dist_client_components_builtin_global-error_cfec7764.js")
R.c("server/chunks/ssr/Documents_Projects_getsucces_app_layout_tsx_30c94e94._.js")
R.c("server/chunks/ssr/51311_next_dist_client_components_062dc819._.js")
R.c("server/chunks/ssr/51311_next_dist_client_components_builtin_forbidden_985fca4f.js")
R.c("server/chunks/ssr/51311_next_dist_client_components_builtin_unauthorized_b67ae914.js")
R.c("server/chunks/ssr/Documents_Projects_getsucces__next-internal_server_app_page_actions_974966c9.js")
R.m(43048)
module.exports=R.m(43048).exports
